<?php
class UrlTransliterate
{
    public static function cleanString($string, $separator = '-',$cleanPunctuation = TRUE, $cleanSlash = TRUE)
    {
        // Default words to ignore
        /*$ignoreWords = array(
            'an', 'as', 'at', 'before', 'but', 'by', 'for', 'from', 'is', 'in',
            'into', 'like', 'of', 'off', 'on', 'onto', 'per', 'since', 'than', 'the',
            'this', 'that', 'to', 'up', 'via', 'with',
        );*/
        
        $ignoreWords = array();

        $output = $string;
        if ($cleanPunctuation)
        {
            $punctuation = self::punctuationChars();
            foreach ($punctuation as $name => $details) 
            {
              if(isset ($details['value'])){
                
                // Slightly tricky inline if which either replaces with the separator or nothing
                $output = str_replace($details['value'], $separator, $output);
              }
                
            }
        }

        // If something is already urlsafe then don't remove slashes
        if ($cleanSlash) 
        {
            $output = str_replace('/', '', $output);
        }

        // Optionally remove accents and transliterate
        $translations = self::$_utf8_accents;
        $output = strtr($output, $translations);

        // Reduce to the subset of ASCII96 letters and numbers
        //$pattern = '/[^a-zA-Z0-9\/]+/ ';
        //$output = preg_replace($pattern, $separator, $output);

        // Get rid of words that are on the ignore list
        $ignoreWords = implode(',' , $ignoreWords);
        $ignoreRe = '\b'. preg_replace('/,/', '\b|\b', $ignoreWords) .'\b';

        if (function_exists('mb_eregi_replace')) 
        {
            $output = mb_eregi_replace($ignoreRe, '', $output);
        }
        else 
        {
            $output = preg_replace("/$ignoreRe/i", '', $output);
        }

        // Always replace whitespace with the separator.
        $output = preg_replace('/\s+/', $separator, $output);

        // Trim duplicates and remove trailing and leading separators.
        $output = self::cleanSeparators($output, $separator);

        // Enforce the maximum component length
        //$maxlength = 128;
        //$output = substr($output, 0, $maxlength);

        return $output;
        
    }

     /**
     * Clean path separators from a given string.
     *
     * Trims duplicates and strips leading and trailing separators.
     *
     * @param $string
     *   The string to clean path separators from.
     * @param $separator
     *   The path separator to use when cleaning.
     * @return
     *   The cleaned version of the string.
     *
     * @see pathauto_cleanstring()
     * @see pathauto_clean_alias()
     */
    public static function cleanSeparators($string, $separator = NULL, $toLowCase = TRUE) 
    {
        $output = $string;

        // Clean duplicate or trailing separators.
        if (isset($separator) && strlen($separator)) 
        {
            // Escape the separator.
            $seppattern = preg_quote($separator, '/');

            // Trim any leading or trailing separators.
            $output = preg_replace("/^$seppattern+|$seppattern+$/", '', $output);

            // Replace trailing separators around slashes.
            $output = preg_replace("/$seppattern+\/|\/$seppattern+/", "/", $output);

            // Replace multiple separators with a single one.
            $output = preg_replace("/$seppattern+/", $separator, $output);
        }

        // Optionally convert to lower case.
        if ($toLowCase) 
        {
            $output = strtolower($output);
        }

        return $output;
    }   

    /**
     * Return an array of arrays for punctuation values.
     *
     * Returns an array of arrays for punctuation values keyed by a name, including
     * the value and a textual description.
     * Can and should be expanded to include "all" non text punctuation values.
     *
     * @return
     *   An array of arrays for punctuation values keyed by a name, including the
     *   value and a textual description.
     */
    public static function punctuationChars() 
    {
        // Handle " ' ` , . - _ : ; | { [ } ] + = * & % ^ $ # @ ! ~ ( ) ? < > \
        return array(
            "double_quotes"=>'"',
            "quotes"=>"'",
            "backtick"=>"`",
            "comma"=>",",
            "period"=>".",
            "hyphen"=>"-",
            "underscore"=>"_",
            "colon"=>":",
            "semicolon"=>";",
            "pipe"=>"|",
            "left_curly"=>"{",
            "left_square"=>"[",
            "right_curly"=>"}",
            "right_square"=>"]",
            "plus"=>"+",
            "equal"=>"=",
            "asterisk"=>"*",
            "ampersand"=>"&",
            "percent"=>"%",
            "caret"=>"^",
            "dollar"=>"$",
            "hash"=>"#",
            "at"=>"@",
            "exclamation"=>"!",
            "tilde"=>"~",
            "left_parenthesis"=>"(",
            "right_parenthesis"=>")",
            "question_mark"=>"?",
            "less_than"=>"<",
            "greater_than"=>">",
            "back_slash"=>'\\',
        );
    } 

    private static $_utf8_accents = array(
		'à' => 'a', 'á' => 'a', 'ả' => 'a', 'ã' => 'a', 'ạ' => 'a',
		'À' => 'A', 'Á' => 'A', 'Ả' => 'A', 'Ã' => 'A', 'Ạ' => 'A',
		'â' => 'a', 'ầ' => 'a', 'ấ' => 'a', 'ẩ' => 'a', 'ẫ' => 'a', 'ậ' => 'a',
		'Â' => 'A', 'Ầ' => 'A', 'Ấ' => 'A', 'Ẩ' => 'A', 'Ẫ' => 'A', 'Ậ' => 'A',
		'ă' => 'a', 'ằ' => 'a', 'ắ' => 'a', 'ẳ' => 'a', 'ẵ' => 'a', 'ặ' => 'a',
		'Ă' => 'A', 'Ằ' => 'A', 'Ắ' => 'A', 'Ẳ' => 'A', 'Ẵ' => 'A', 'Ặ' => 'A',
		'ā' => 'a', 'ą' => 'a', 'å' => 'a', 'ä' => 'a',
		'Ā' => 'A', 'Ą' => 'A', 'Å' => 'A', 'Ä' => 'A',
		'ḃ' => 'b', 'Ḃ' => 'B',
		'ç' => 'c', 'ċ' => 'c', 'ĉ' => 'c', 'ć' => 'c', 'č' => 'c',
		'Ç' => 'C', 'Ċ' => 'C', 'Ĉ' => 'C', 'Ć' => 'C', 'Č' => 'C',
		'đ' => 'd', 'Đ' => 'D', 'ď' => 'd', 'Ď' => 'D', 'ḋ' => 'd', 'Ḋ' => 'D',
		'è' => 'e', 'é' => 'e', 'ẻ' => 'e', 'ẽ' => 'e', 'ẹ' => 'e',
		'È' => 'E', 'É' => 'E', 'Ẻ' => 'E', 'Ẽ' => 'E', 'Ẹ' => 'E',
		'ê' => 'e', 'ề' => 'e', 'ế' => 'e', 'ể' => 'e', 'ễ' => 'e', 'ệ' => 'e',
		'Ê' => 'E', 'Ề' => 'E', 'Ế' => 'E', 'Ể' => 'E', 'Ễ' => 'E', 'Ệ' => 'E',
		'ë' => 'e', 'ě' => 'e', 'ė' => 'e', 'ę' => 'e', 'ē' => 'e', 'ĕ' => 'e',
		'Ë' => 'E', 'Ě' => 'E', 'Ė' => 'E', 'Ę' => 'E', 'Ē' => 'E', 'Ĕ' => 'E',
		'ḟ' => 'f', 'ƒ' => 'f', 'Ḟ' => 'F', 'Ƒ' => 'F',
		'ģ' => 'g', 'ğ' => 'g', 'ĝ' => 'g', 'ġ' => 'g',
		'Ģ' => 'G', 'Ğ' => 'G', 'Ĝ' => 'G', 'Ġ' => 'G',
		'ħ' => 'h', 'ĥ' => 'h', 'Ħ' => 'H', 'Ĥ' => 'H',
		'ì' => 'i', 'í' => 'i', 'ỉ' => 'i', 'ĩ' => 'i', 'ị' => 'i',
		'Ì' => 'I', 'Í' => 'I', 'Ỉ' => 'I', 'Ĩ' => 'I', 'Ị' => 'I',
		'î' => 'i', 'ï' => 'i', 'ī' => 'i', 'į' => 'i',
		'Î' => 'I', 'Ï' => 'I', 'Ī' => 'I', 'Į' => 'I',
		'ĵ' => 'j', 'Ĵ' => 'J',
		'ķ' => 'k', 'Ķ' => 'K',
		'ĺ' => 'l', 'ł' => 'l', 'ļ' => 'l', 'ľ' => 'l',
		'Ĺ' => 'L', 'Ł' => 'L', 'Ļ' => 'L', 'Ľ' => 'L',
		'ṁ' => 'm', 'Ṁ' => 'M', 
		'ň' => 'n', 'ņ' => 'n', 'ñ' => 'n', 'ń' => 'n',
		'Ň' => 'N', 'Ņ' => 'N', 'Ñ' => 'N', 'Ń' => 'N',
		'ò' => 'o', 'ó' => 'o', 'ỏ' => 'o', 'õ' => 'o', 'ọ' => 'o',
		'Ò' => 'O', 'Ó' => 'O', 'Ỏ' => 'O', 'Õ' => 'O', 'Ọ' => 'O',
		'ô' => 'o', 'ồ' => 'o', 'ố' => 'o', 'ổ' => 'o', 'ỗ' => 'o', 'ộ' => 'o',
		'Ô' => 'O', 'Ồ' => 'O', 'Ố' => 'O', 'Ổ' => 'O', 'Ỗ' => 'O', 'Ộ' => 'O', 
		'ơ' => 'o', 'ờ' => 'o', 'ớ' => 'o', 'ở' => 'o', 'ỡ' => 'o', 'ợ' => 'o',
		'Ơ' => 'O', 'Ờ' => 'O', 'Ớ' => 'O', 'Ở' => 'O', 'Ỡ' => 'O', 'Ợ' => 'O',
		'ø' => 'o', 'ö' => 'o', 'ő' => 'o', 'ō' => 'o',
		'Ø' => 'O', 'Ö' => 'O', 'Ő' => 'O', 'Ō' => 'O',
		'ṗ' => 'p', 'Ṗ' => 'P',
		'ř' => 'r', 'ŗ' => 'r', 'ŕ' => 'r',
		'Ř' => 'R', 'Ŗ' => 'R', 'Ŕ' => 'R',
		'š' => 's', 'ŝ' => 's', 'ṡ' => 's', 'ș' => 's', 'ś' => 's', 'ş' => 's',
		'Š' => 'S', 'Ŝ' => 'S', 'Ṡ' => 'S', 'Ș' => 'S', 'Ś' => 'S', 'Ş' => 'S',
		'ț' => 't', 'ŧ' => 't', 'ṫ' => 't', 'ť' => 't', 'ţ' => 't',
		'Ț' => 'T', 'Ŧ' => 'T', 'Ṫ' => 'T', 'Ť' => 'T', 'Ţ' => 'T',
		'ù' => 'u', 'ú' => 'u', 'ủ' => 'u', 'ũ' => 'u', 'ụ' => 'u',
		'Ù' => 'U', 'Ú' => 'U', 'Ủ' => 'U', 'Ũ' => 'U', 'Ụ' => 'U',
		'ư' => 'u', 'ừ' => 'u', 'ứ' => 'u', 'ử' => 'u', 'ữ' => 'u', 'ự' => 'u',
		'Ư' => 'U', 'Ừ' => 'U', 'Ứ' => 'U', 'Ử' => 'U', 'Ữ' => 'U', 'Ự' => 'U',
		'ű' => 'u', 'ū' => 'u', 'ų' => 'u', 'ů' => 'u', 'ü' => 'u', 'ŭ' => 'u', 'û' => 'u', 'µ' => 'u',
		'Ű' => 'U', 'Ū' => 'U', 'Ų' => 'U', 'Ů' => 'U', 'Ü' => 'U', 'Ŭ' => 'U', 'Û' => 'U', 'µ' => 'U',
		'ẁ' => 'w', 'ŵ' => 'w', 'ẃ' => 'w', 'ẅ' => 'w',
		'Ẁ' => 'W', 'Ŵ' => 'W', 'Ẃ' => 'W', 'Ẅ' => 'W',
		'ỳ' => 'y', 'ý' => 'y', 'ỷ' => 'y', 'ỹ' => 'y', 'ỵ' => 'y',
		'Ỳ' => 'Y', 'Ý' => 'Y', 'Ỷ' => 'Y', 'Ỹ' => 'Y', 'Ỵ' => 'Y',
		'ŷ' => 'y', 'ÿ' => 'y', 'Ŷ' => 'Y', 'Ÿ' => 'Y',
		'ž' => 'z', 'ż' => 'z', 'ź' => 'z',
		'Ž' => 'Z', 'Ż' => 'Z', 'Ź' => 'Z',
		'ß' => 'ss', 'þ' => 'th', 'ð' => 'dh', 'æ' => 'ae',
		'Þ' => 'Th', 'Ð' => 'Dh', 'Æ' => 'Ae',
		',' =>'_',
                "'" => '-',
                '.' => ''
	);
    
    public static function i18nToAscII()
    {
        return array(
            "À" => "A",'Ă'=>'A','Ặ'=>'A',
            "Á" => "A",
            "Â" => "A",
            "Ã" => "A",
            "Ä" => "Ae",
            "Å" => "A",
            "Æ" => "A",
            "Ā" => "A",
            "Ą" => "A",
            "Ă" => "A",
            "Ç" => "C",
            "Ć" => "C",
            "Č" => "C",
            "Ĉ" => "C",
            "Ċ" => "C",
            "Ď" => "D",
            "Đ" => "D",
            "È" => "E","Ệ"=>'E',"Ễ"=>'E',"Ế"=>'E',"Ễ"=>'E',
            "É" => "E",
            "Ê" => "E",
        	"Ệ" => "E",
            "Ë" => "E",
            "Ē" => "E",
            "Ę" => "E",
            "Ě" => "E",
            "Ĕ" => "E",
            "Ė" => "E",
            "Ĝ" => "G",
            "Ğ" => "G",
            "Ġ" => "G",
            "Ģ" => "G",
            "Ĥ" => "H",
            "Ħ" => "H",
            "Ì" => "I",
            "Í" => "I",
            "Î" => "I",
            "Ï" => "I",
            "Ī" => "I",
            "Ĩ" => "I",
            "Ĭ" => "I",
            "Į" => "I",
            "İ" => "I",
            "Ĳ" => "IJ",
            "Ĵ" => "J",
            "Ķ" => "K",
            "Ľ" => "K",
            "Ĺ" => "K",
            "Ļ" => "K",
            "Ŀ" => "K",
            "Ł" => "L",
            "Ñ" => "N",
            "Ń" => "N",
            "Ň" => "N",
            "Ņ" => "N",
            "Ŋ" => "N",
            "Ò" => "O",
            "Ó" => "O",
        	"Ơ" => "O",
            "Ô" => "O",
            "Õ" => "O",
        	"Ờ" =>	"O",
            "Ö" => "Oe",
            "Ø" => "O",
            "Ō" => "O",
            "Ő" => "O",
            "Ŏ" => "O",
            "Œ" => "OE",
            "Ŕ" => "R",
            "Ř" => "R",
            "Ŗ" => "R",
            "Ś" => "S",
            "Ş" => "S",
            "Ŝ" => "S",
            "Ș" => "S",
            "Š" => "S",
            "Ť" => "T",
            "Ţ" => "T",
            "Ŧ" => "T",
            "Ț" => "T",
            "Ù" => "U",
        	"Ư" => "U",
        	"Ụ" => "U",
            "Ú" => "U",
            "Û" => "U",
            "Ü" => "Ue",
            "Ū" => "U",
            "Ů" => "U","Ữ"=>'U',"Ụ"=>'U','Ư'=>'U','Ừ'=>'U',
            "Ű" => "U",
            "Ŭ" => "U",
            "Ũ" => "U",
            "Ų" => "U",
            "Ŵ" => "W",
            "Ŷ" => "Y",
            "Ÿ" => "Y",
            "Ý" => "Y",
            "Ź" => "Z",
            "Ż" => "Z",
            "Ž" => "Z",
            "à" => "a",
            "á" => "a",
            "â" => "a",
            "ã" => "a",
            "ä" => "ae",
            "ā" => "a",
            "ą" => "a",
            "ă" => "a",
            "å" => "a",
            "æ" => "ae",
            "ç" => "c",
            "ć" => "c",
            "č" => "c",
            "ĉ" => "c",
            "ċ" => "c",
            "ď" => "d",
            "đ" => "d",
            "è" => "e",
            "é" => "e",
            "ê" => "e",
            "ë" => "e",
            "ē" => "e",
            "ę" => "e",
            "ě" => "e",
            "ĕ" => "e",
            "ė" => "e",
            "ƒ" => "f",
            "ĝ" => "g",
            "ğ" => "g",
            "ġ" => "g",
            "ģ" => "g",
            "ĥ" => "h",
            "ħ" => "h",
            "ì" => "i",
            "í" => "i",
            "î" => "i",
            "ï" => "i",
            "ī" => "i",
            "ĩ" => "i",
            "ĭ" => "i",
            "į" => "i",
            "ı" => "i",
            "ĳ" => "ij",
            "ĵ" => "j",
            "ķ" => "k",
            "ĸ" => "k",
            "ł" => "l",
            "ľ" => "l",
            "ĺ" => "l",
            "ļ" => "l",
            "ŀ" => "l",
            "ñ" => "n",
            "ń" => "n",
            "ň" => "n",
            "ņ" => "n",
            "ŉ" => "n",
            "ŋ" => "n",
            "ò" => "o",
            "ó" => "o",
            "ô" => "o",
            "õ" => "o",
            "ö" => "oe",
            "ø" => "o",
            "ō" => "o",
            "ő" => "o",
            "ŏ" => "o",
            "œ" => "oe",
            "ŕ" => "r",
            "ř" => "r",
            "ŗ" => "r",
            "ś" => "s",
            "š" => "s",
            "ş" => "s",
            "ť" => "t",
            "ţ" => "t",
            "ù" => "u",
            "ú" => "u",
            "û" => "u",
            "ü" => "ue",
            "ū" => "u",
            "ů" => "u",
            "ű" => "u",
            "ŭ" => "u",
            "ũ" => "u",
            "ų" => "u",
            "ŵ" => "w",
            "ÿ" => "y",
            "ý" => "y",
            "ŷ" => "y",
            "ż" => "z",
            "ź" => "z",
            "ž" => "z",
            "ß" => "ss",
            "ſ" => "ss",
            "Α" => "A",
            "Ά" => "A",
            "Ἀ" => "A",
            "Ἁ" => "A",
            "Ἂ" => "A",
            "Ἃ" => "A",
            "Ἄ" => "A",
            "Ἅ" => "A",
            "Ἆ" => "A",
            "Ἇ" => "A",
            "ᾈ" => "A",
            "ᾉ" => "A",
            "ᾊ" => "A",
            "ᾋ" => "A",
            "ᾌ" => "A",
            "ᾍ" => "A",
            "ᾎ" => "A",
            "ᾏ" => "A",
            "Ᾰ" => "A",
            "Ᾱ" => "A",
            "Ὰ" => "A",
            "Ά" => "A",
            "ᾼ" => "A",
            "Β" => "B",
            "Γ" => "G",
            "Δ" => "D",
            "Ε" => "E",
            "Έ" => "E",
            "Ἐ" => "E",
            "Ἑ" => "E",
            "Ἒ" => "E",
            "Ἓ" => "E",
            "Ἔ" => "E",
            "Ἕ" => "E",
            "Έ" => "E",
            "Ὲ" => "E",
            "Ζ" => "Z",
            "Η" => "I",
            "Ή" => "I",
            "Ἠ" => "I",
            "Ἡ" => "I",
            "Ἢ" => "I",
            "Ἣ" => "I",
            "Ἤ" => "I",
            "Ἥ" => "I",
            "Ἦ" => "I",
            "Ἧ" => "I",
            "ᾘ" => "I",
            "ᾙ" => "I",
            "ᾚ" => "I",
            "ᾛ" => "I",
            "ᾜ" => "I",
            "ᾝ" => "I",
            "ᾞ" => "I",
            "ᾟ" => "I",
            "Ὴ" => "I",
            "Ή" => "I",
            "ῌ" => "I",
            "Θ" => "TH",
            "Ι" => "I",
            "Ί" => "I",
            "Ϊ" => "I",
            "Ἰ" => "I",
            "Ἱ" => "I",
            "Ἲ" => "I",
            "Ἳ" => "I",
            "Ἴ" => "I",
            "Ἵ" => "I",
            "Ἶ" => "I",
            "Ἷ" => "I",
            "Ῐ" => "I",
            "Ῑ" => "I",
            "Ὶ" => "I",
            "Ί" => "I",
            "Κ" => "K",
            "Λ" => "L",
            "Μ" => "M",
            "Ν" => "N",
            "Ξ" => "KS",
            "Ο" => "O",
            "Ό" => "O",
            "Ὀ" => "O",
            "Ὁ" => "O",
            "Ὂ" => "O",
            "Ὃ" => "O",
            "Ὄ" => "O",
            "Ὅ" => "O",
            "Ὸ" => "O",
            "Ό" => "O",
            "Π" => "P",
            "Ρ" => "R",
            "Ῥ" => "R",
            "Σ" => "S",
            "Τ" => "T",
            "Υ" => "Y",
            "Ύ" => "Y",
            "Ϋ" => "Y",
            "Ὑ" => "Y",
            "Ὓ" => "Y",
            "Ὕ" => "Y",
            "Ὗ" => "Y",
            "Ῠ" => "Y",
            "Ῡ" => "Y",
            "Ὺ" => "Y",
            "Ύ" => "Y",
            "Φ" => "F",
            "Χ" => "X",
            "Ψ" => "PS",
            "Ω" => "O",
            "Ώ" => "O",
            "Ὠ" => "O",
            "Ὡ" => "O",
            "Ὢ" => "O",
            "Ὣ" => "O",
            "Ὤ" => "O",
            "Ὥ" => "O",
            "Ὦ" => "O",
            "Ὧ" => "O",
            "ᾨ" => "O",
            "ᾩ" => "O",
            "ᾪ" => "O",
            "ᾫ" => "O",
            "ᾬ" => "O",
            "ᾭ" => "O",
            "ᾮ" => "O",
            "ᾯ" => "O",
            "Ὼ" => "O",
            "Ώ" => "O",
            "ῼ" => "O",
            "α" => "a",
            "ά" => "a",
            "ἀ" => "a",
            "ἁ" => "a",
            "ἂ" => "a",
            "ἃ" => "a",
            "ἄ" => "a",
            "ἅ" => "a",
            "ἆ" => "a",
            "ἇ" => "a",
            "ᾀ" => "a",
            "ᾁ" => "a",
            "ᾂ" => "a",
            "ᾃ" => "a",
            "ᾄ" => "a",
            "ᾅ" => "a",
            "ᾆ" => "a",
            "ᾇ" => "a",
            "ὰ" => "a",
            "ά" => "a",
            "ᾰ" => "a",
            "ᾱ" => "a",
            "ᾲ" => "a",
            "ᾳ" => "a",
            "ᾴ" => "a",
            "ᾶ" => "a",
            "ᾷ" => "a",
            "β" => "b",
            "γ" => "g",
            "δ" => "d",
            "ε" => "e",
            "έ" => "e",
            "ἐ" => "e",
            "ἑ" => "e",
            "ἒ" => "e",
            "ἓ" => "e",
            "ἔ" => "e",
            "ἕ" => "e",
            "ὲ" => "e",
            "έ" => "e",
            "ζ" => "z",
            "η" => "i",
            "ή" => "i",
            "ἠ" => "i",
            "ἡ" => "i",
            "ἢ" => "i",
            "ἣ" => "i",
            "ἤ" => "i",
            "ἥ" => "i",
            "ἦ" => "i",
            "ἧ" => "i",
            "ᾐ" => "i",
            "ᾑ" => "i",
            "ᾒ" => "i",
            "ᾓ" => "i",
            "ᾔ" => "i",
            "ᾕ" => "i",
            "ᾖ" => "i",
            "ᾗ" => "i",
            "ὴ" => "i",
            "ή" => "i",
            "ῂ" => "i",
            "ῃ" => "i",
            "ῄ" => "i",
            "ῆ" => "i",
            "ῇ" => "i",
            "θ" => "th",
            "ι" => "i",
            "ί" => "i",
            "ϊ" => "i",
            "ΐ" => "i",
            "ἰ" => "i",
            "ἱ" => "i",
            "ἲ" => "i",
            "ἳ" => "i",
            "ἴ" => "i",
            "ἵ" => "i",
            "ἶ" => "i",
            "ἷ" => "i",
            "ὶ" => "i",
            "ί" => "i",
            "ῐ" => "i",
            "ῑ" => "i",
            "ῒ" => "i",
            "ΐ" => "i",
            "ῖ" => "i",
            "ῗ" => "i",
            "κ" => "k",
            "λ" => "l",
            "μ" => "m",
            "ν" => "n",
            "ξ" => "ks",
            "ο" => "o",
            "ό" => "o",
            "ὀ" => "o",
            "ὁ" => "o",
            "ὂ" => "o",
            "ὃ" => "o",
            "ὄ" => "o",
            "ὅ" => "o",
            "ὸ" => "o",
            "ό" => "o",
            "π" => "p",
            "ρ" => "r",
            "ῤ" => "r",
            "ῥ" => "r",
            "σ" => "s",
            "ς" => "s",
            "τ" => "t",
            "υ" => "y",
            "ύ" => "y",
            "ϋ" => "y",
            "ΰ" => "y",
            "ὐ" => "y",
            "ὑ" => "y",
            "ὒ" => "y",
            "ὓ" => "y",
            "ὔ" => "y",
            "ὕ" => "y",
            "ὖ" => "y",
            "ὗ" => "y",
            "ὺ" => "y",
            "ύ" => "y",
            "ῠ" => "y",
            "ῡ" => "y",
            "ῢ" => "y",
            "ΰ" => "y",
            "ῦ" => "y",
            "ῧ" => "y",
            "φ" => "f",
            "χ" => "x",
            "ψ" => "ps",
            "ω" => "o",
            "ώ" => "o",
            "ὠ" => "o",
            "ὡ" => "o",
            "ὢ" => "o",
            "ὣ" => "o",
            "ὤ" => "o",
            "ὥ" => "o",
            "ὦ" => "o",
            "ὧ" => "o",
            "ᾠ" => "o",
            "ᾡ" => "o",
            "ᾢ" => "o",
            "ᾣ" => "o",
            "ᾤ" => "o",
            "ᾥ" => "o",
            "ᾦ" => "o",
            "ᾧ" => "o",
            "ὼ" => "o",
            "ώ" => "o",
            "ῲ" => "o",
            "ῳ" => "o",
            "ῴ" => "o",
            "ῶ" => "o",
            "ῷ" => "o",
            "¨" => "",
            "΅" => "",
            "᾿" => "",
            "῾" => "",
            "῍" => "",
            "῝" => "",
            "῎" => "",
            "῞" => "",
            "῏" => "",
            "῟" => "",
            "῀" => "",
            "῁" => "",
            "΄" => "",
            "΅" => "",
            "`" => "",
            "῭" => "",
            "ͺ" => "",
            "᾽" => "",
            "А" => "A",
            "Б" => "B",
            "В" => "V",
            "Г" => "G",
            "Д" => "D",
            "Е" => "E",
            "Ё" => "E",
            "Ж" => "ZH",
            "З" => "Z",
            "И" => "I",
            "Й" => "I",
            "К" => "K",
            "Л" => "L",
            "М" => "M",
            "Н" => "N",
            "О" => "O",
            "П" => "P",
            "Р" => "R",
            "С" => "S",
            "Т" => "T",
            "У" => "U",
            "Ф" => "F",
            "Х" => "KH",
            "Ц" => "TS",
            "Ч" => "CH",
            "Ш" => "SH",
            "Щ" => "SHCH",
            "Ы" => "Y",
            "Э" => "E",
            "Ю" => "YU",
            "Я" => "YA",
            "а" => "A",
            "б" => "B",
            "в" => "V",
            "г" => "G",
            "д" => "D",
            "е" => "E",
            "ё" => "E",
            "ж" => "ZH",
            "з" => "Z",
            "и" => "I",
            "й" => "I",
            "к" => "K",
            "л" => "L",
            "м" => "M",
            "н" => "N",
            "о" => "O",
            "п" => "P",
            "р" => "R",
            "с" => "S",
            "т" => "T",
            "у" => "U",
            "ф" => "F",
            "х" => "KH",
            "ц" => "TS",
            "ч" => "CH",
            "ш" => "SH",
            "щ" => "SHCH",
            "ы" => "Y",
            "э" => "E",
            "ю" => "YU",
            "я" => "YA",
            "Ъ" => "",
            "ъ" => "",
            "Ь" => "",
            "ь" => "",
            "ð" => "d",
            "Ð" => "D",
            "þ" => "th",
            "Þ" => "TH" 
        );
    }
    
    public static function truncate($str, $len) {
        $tail = max(0, $len-10);
        $trunk = substr($str, 0, $tail);
        $trunk .= strrev(preg_replace('~^..+?[\s,:]\b|^...~', '...', strrev(substr($str, $tail, $len-$tail))));
        return $trunk;
    }
}