<?php

/**
 * This is the model base class for the table "shop_manufacturer".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ShopManufacturer".
 *
 * Columns in table "shop_manufacturer" available as properties of the model,
 * followed by relations of table "shop_manufacturer" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property string $address
 * @property string $email
 * @property integer $status
 *
 * @property ShopProducts[] $shopProducts
 */
abstract class BaseShopManufacturer extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'shop_manufacturer';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Manufacturer');
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('status', 'numerical', 'integerOnly'=>true),
			array('name, address, email', 'length', 'max'=>255),
			array('name, address, email, status', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, address, email, status', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'shopProducts' => array(self::HAS_MANY, 'ShopProduct', 'manufacturer_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'address' => Yii::t('app', 'Address'),
			'email' => Yii::t('app', 'Email'),
			'status' => Yii::t('app', 'Status'),
			'shopProducts' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('address', $this->address, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('status', $this->status);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}