<?php

/**
 * This is the model base class for the table "agency".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Agency".
 *
 * Columns in table "agency" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $name
 * @property string $address
 * @property string $phone
 * @property string $fax
 * @property string $email
 * @property integer $status
 * @property string $url_map
 * @property string $created_at
 * @property string $updated_at
 *
 */
abstract class BaseAgency extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'agency';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Agency|Agencies', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('status', 'numerical', 'integerOnly'=>true),
			array('name, phone, fax, email, url_map', 'length', 'max'=>255),
			array('address', 'length', 'max'=>512),
			array('created_at, updated_at', 'safe'),
			array('name, address, phone, fax, email, status, url_map, created_at, updated_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, address, phone, fax, email, status, url_map, created_at, updated_at', 'safe', 'on'=>'search'),
            array('email', 'email'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'address' => Yii::t('app', 'Address'),
			'phone' => Yii::t('app', 'Phone'),
			'fax' => Yii::t('app', 'Fax'),
			'email' => Yii::t('app', 'Email'),
			'status' => Yii::t('app', 'Status'),
			'url_map' => Yii::t('app', 'Url Map'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('address', $this->address, true);
		$criteria->compare('phone', $this->phone, true);
		$criteria->compare('fax', $this->fax, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('status', $this->status);
		$criteria->compare('url_map', $this->url_map, true);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}